
version: '3.8'

services:
  postgredb:
    image: postgres
    hostname: ${POSTGRES_ENV_HOSTNAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ENV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ENV_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ENV_DATABASE}
    volumes:
      - ./dockerutils/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_ENV_PORT}:${POSTGRES_ENV_PORT}"
    command: -p ${POSTGRES_ENV_PORT}
  
  cartefede:
    container_name: cartefede
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgredb
    env_file: .env
